ARG UV_VERSION=0.10



######################################
# BASE
FROM python:3.12.1-slim-bookworm AS base

COPY --from=ghcr.io/astral-sh/uv:0.10 /uv /usr/local/bin/uv
ENV UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1 \
    UV_PROJECT_ENVIRONMENT=/opt/venv
ENV PATH="/opt/venv/bin:${PATH}"



######################################
# BUILDER
FROM base AS builder

WORKDIR /tmp

RUN apt-get update && \
    apt-get install -y \
    libpq-dev \
    gcc && \
    rm -rf /var/lib/apt/lists/*

COPY ./zpodapi/pyproject.toml ./zpodapi/uv.lock /tmp/
RUN uv sync --frozen --no-install-project



######################################
# MAIN
FROM base AS main

RUN apt-get update && \
    apt-get install -y \
    libpq5 \
    git && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /opt/venv /opt/venv

ENV PYTHONPATH=/zpodcore/src

WORKDIR /zpodcore
CMD ["tail", "-f", "/dev/null"]



######################################
# DEV
FROM main AS dev
CMD ["python", "/zpodcore/scripts/startup/start_reload.py"]



######################################
# PROD
FROM main AS production
COPY ./zpodapi/scripts /zpodcore/scripts
COPY ./zpodapi/tests /zpodcore/tests
COPY ./zpodapi/src/zpodapi /zpodcore/src/zpodapi
COPY ./zpodcommon/src/zpodcommon /zpodcore/src/zpodcommon
CMD ["python", "/zpodcore/scripts/startup/start.py"]
