version: '3.7'
services:
  zpodapi:
    container_name: ${COMPOSE_PROJECT_NAME}-zpodapi
    build:
      context: .
      dockerfile: ./zpodapi/dockerfile
      target: dev
      args:
        INSTALL_DEV: "${ZPODAPI_DEV_MODE:-false}"
    depends_on:
      - zpodpostgres
    env_file:
      - .env
    environment:
      - COLUMNS
      - HISTFILE=/commandhistory/.zpodapi_bash_history
      - PYDEVD_DISABLE_FILE_VALIDATION=1
    init: true
    ports:
      - ${ZPODAPI_HOSTPORT:-127.0.0.1:8000}:8000
      - ${ZPODAPI_DEBUG_HOSTPORT:-127.0.0.1:5678}:5678
    restart: always
    tty: true
    # user: "${UID}:${GID}"
    volumes:
      - ./zpodapi/scripts:/zpodcore/scripts:cached
      - ./zpodapi/tests:/zpodcore/tests:cached
      - ./zpodapi/src/zpodapi:/zpodcore/src/zpodapi:cached
      - ./zpodcommon/src/zpodcommon:/zpodcore/src/zpodcommon:cached
      - ${ZPODCORE_LIBRARY_PATH}:/library
      - ${ZPODCORE_PRODUCTS_PATH}:/products
      - ./logs:/zpodcore/logs:cached
      - zpod_vol_history:/commandhistory

  zpodpostgres:
    container_name: ${COMPOSE_PROJECT_NAME}-zpodpostgres
    environment:
      - POSTGRES_PASSWORD=${ZPODCORE_POSTGRES_PASSWORD}
    build:
      context: .
      dockerfile: ./zpodpostgres/dockerfile
    command: [ "postgres", "--log_checkpoints=0" ]
    ports:
      - ${ZPODAPI_POSTGRES_HOSTPORT:-127.0.0.1:5432}:5432
    restart: always
    volumes:
      - zpod_vol_postgres:/var/lib/postgresql/data

  # Prefect Server API
  zpodengineserver:
    container_name: ${COMPOSE_PROJECT_NAME}-zpodengineserver
    image: prefecthq/prefect:2.10.4-python3.11
    depends_on:
      - zpodpostgres
    entrypoint: [ "prefect", "server", "start" ]
    environment:
      - PREFECT_API_URL=http://${ZPODENGINE_HOSTPORT:-127.0.0.1:4200}/api
      # Keeping those variables for potential future tuning
      - PREFECT_API_DATABASE_TIMEOUT=30
      - PREFECT_API_DATABASE_CONNECTION_TIMEOUT=15
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:${ZPODCORE_POSTGRES_PASSWORD}@zpodpostgres/prefect
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - TELEMETRY_ENABLED=false
    ports:
      - ${ZPODENGINE_HOSTPORT:-127.0.0.1:4200}:4200
    restart: always
    volumes:
      - zpod_vol_prefect:/root/.prefect

  # Prefect Agent
  zpodengineagent:
    container_name: ${COMPOSE_PROJECT_NAME}-zpodengineagent
    image: prefecthq/prefect:2.10.4-python3.11
    depends_on:
      - zpodpostgres
    entrypoint:
      [
        "prefect",
        "agent",
        "start",
        "-q",
        "default",
        #"--limit",
        #"1"
      ]
    environment:
      - PREFECT_API_URL=http://zpodengineserver:4200/api
      # Keeping those variables for potential future tuning.
      - PREFECT_API_DATABASE_TIMEOUT=30
      - PREFECT_API_DATABASE_CONNECTION_TIMEOUT=15
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Prefect CLI
  zpodenginecli:
    container_name: ${COMPOSE_PROJECT_NAME}-zpodenginecli
    build:
      context: .
      dockerfile: ./zpodengine/dockerfile
      target: dev
      args:
        INSTALL_DEV: "${ZPODENGINE_DEV_MODE:-false}"
    depends_on:
      - zpodpostgres
    entrypoint: [ "/bin/bash" ]
    environment:
      - PREFECT_API_URL=http://zpodengineserver:4200/api
      - ZPODCORE_PATH=${PWD}
      - HISTFILE=/commandhistory/.zpodenginecli_bash_history
    env_file:
      - .env
    profiles: [ "cli" ]
    volumes:
      - ./zpodcommon/src/zpodcommon:/zpodcore/src/zpodcommon:cached
      - ./zpodengine/src/zpodengine:/zpodcore/src/zpodengine:cached
      - ./zpodengine/scripts:/zpodcore/scripts:cached
      - zpod_vol_history:/commandhistory
      - ${ZPODCORE_LIBRARY_PATH}:/library
      - ${ZPODCORE_PRODUCTS_PATH}:/products
      - ${ZPODCORE_DNSMASQ_PATH}:/etc/dnsmasq.d

volumes:
  zpod_vol_history: null
  zpod_vol_postgres: null
  zpod_vol_prefect: null
