"""update

Revision ID: 0c87e32f129c
Revises: 2f6c907fc8c5
Create Date: 2023-03-07 16:29:29.017727

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "0c87e32f129c"
down_revision = "2f6c907fc8c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
