"""message=update

Revision ID: e7cba7d82ff4
Revises: a231b93c89ed
Create Date: 2023-05-10 18:06:25.826479

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e7cba7d82ff4"
down_revision = "a231b93c89ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("components", sa.Column("active", sa.Boolean(), nullable=False))
    op.alter_column(
        "instance_components", "status", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "instance_components", "status", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("components", "active")
    # ### end Alembic commands ###
