"""component-update

Revision ID: 09672b7ad41d
Revises: e7cba7d82ff4
Create Date: 2023-05-15 16:22:56.475528

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "09672b7ad41d"
down_revision = "e7cba7d82ff4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "components",
        sa.Column("download_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("components", "enabled")
    op.drop_column("components", "active")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "components",
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "components",
        sa.Column("enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("components", "download_status")
    # ### end Alembic commands ###
