"""update

Revision ID: e969a7948284
Revises: 77f096106bb3
Create Date: 2023-03-31 03:17:44.528352

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "e969a7948284"
down_revision = "77f096106bb3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "components",
        sa.Column(
            "component_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("components", "component_description")
    # ### end Alembic commands ###
