"""update

Revision ID: 42aeec43b377
Revises: 4ced08822970
Create Date: 2023-03-31 17:10:59.453160

"""


# revision identifiers, used by Alembic.
revision = "42aeec43b377"
down_revision = "4ced08822970"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
