"""instance_component_ip_hostname_fqdn

Revision ID: cf21e63aeb4f
Revises: 1427af2dd43a
Create Date: 2023-08-22 18:00:40.226240

"""
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "cf21e63aeb4f"
down_revision = "1427af2dd43a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "instance_components",
        sa.Column("ip", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "instance_components",
        sa.Column("hostname", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "instance_components",
        sa.Column("fqdn", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("instance_components", "data")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "instance_components",
        sa.Column(
            "data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("instance_components", "fqdn")
    op.drop_column("instance_components", "hostname")
    op.drop_column("instance_components", "ip")
    # ### end Alembic commands ###
