"""update

Revision ID: 4ced08822970
Revises: 5e58d39f5542
Create Date: 2023-03-31 16:51:16.762886

"""


# revision identifiers, used by Alembic.
revision = "4ced08822970"
down_revision = "5e58d39f5542"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
