"""common_dates

Revision ID: 1c10dbfe6448
Revises: 2f6c907fc8c5
Create Date: 2023-03-15 17:54:42.050130

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1c10dbfe6448"
down_revision = "2f6c907fc8c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "components", sa.Column("creation_date", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "components", sa.Column("last_modified_date", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "libraries", sa.Column("last_modified_date", sa.DateTime(), nullable=False)
    )
    op.drop_column("libraries", "lastupdate_date")
    op.add_column(
        "users", sa.Column("last_modified_date", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "users", sa.Column("last_connection_date", sa.DateTime(), nullable=True)
    )
    op.drop_column("users", "last_connection")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "last_connection",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("users", "last_connection_date")
    op.drop_column("users", "last_modified_date")
    op.add_column(
        "libraries",
        sa.Column(
            "lastupdate_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("libraries", "last_modified_date")
    op.drop_column("components", "last_modified_date")
    op.drop_column("components", "creation_date")
    # ### end Alembic commands ###
