"""inst_comp_status

Revision ID: a231b93c89ed
Revises: 5953ffc1f677
Create Date: 2023-05-02 18:20:45.215860

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "a231b93c89ed"
down_revision = "5953ffc1f677"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "instance_components",
        sa.Column(
            "status",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="ACTIVE",
        ),
    )
    op.alter_column("instance_components", "status", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instance_components", "status")
    # ### end Alembic commands ###
