"""message=added component_name and component_version to db

Revision ID: 2f6c907fc8c5
Revises: 79910b0877c2
Create Date: 2023-03-06 17:10:05.588832

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "2f6c907fc8c5"
down_revision = "79910b0877c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "components",
        sa.Column("component_uid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "components",
        sa.Column("component_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "components",
        sa.Column(
            "component_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.add_column(
        "components",
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_unique_constraint(None, "components", ["component_uid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "components", type_="unique")
    op.drop_column("components", "status")
    op.drop_column("components", "component_version")
    op.drop_column("components", "component_name")
    op.drop_column("components", "component_uid")
    # ### end Alembic commands ###
