"""permissions

Revision ID: 4b74dede5619
Revises: e67c0d042ef8
Create Date: 2023-09-13 19:46:38.501146

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "4b74dede5619"
down_revision = "e67c0d042ef8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "permission_groups", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "permission_groups", type_="unique")
    # ### end Alembic commands ###
