"""update

Revision ID: 5e58d39f5542
Revises: e969a7948284
Create Date: 2023-03-31 14:58:13.432732

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5e58d39f5542"
down_revision = "e969a7948284"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "components",
        "component_description",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "components", "component_description", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
