"""permission

Revision ID: 05a7cece1c44
Revises: 4b74dede5619
Create Date: 2023-09-22 17:43:18.513605

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "05a7cece1c44"
down_revision = "4b74dede5619"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "endpoint_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("permission", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["endpoints.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "endpoint_permission_group_link",
        sa.Column("endpoint_permission_id", sa.Integer(), nullable=False),
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_permission_id"],
            ["endpoint_permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_groups.id"],
        ),
        sa.PrimaryKeyConstraint("endpoint_permission_id", "permission_group_id"),
    )
    op.create_table(
        "endpoint_permission_user_link",
        sa.Column("endpoint_permission_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_permission_id"],
            ["endpoint_permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("endpoint_permission_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("endpoint_permission_user_link")
    op.drop_table("endpoint_permission_group_link")
    op.drop_table("endpoint_permissions")
    # ### end Alembic commands ###
