"""update

Revision ID: 79910b0877c2
Revises: a23e07de84d2
Create Date: 2023-02-15 17:04:30.800488

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "79910b0877c2"
down_revision = "a23e07de84d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "libraries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("git_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("creation_date", sa.DateTime(), nullable=False),
        sa.Column("lastupdate_date", sa.DateTime(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_libraries_name"), "libraries", ["name"], unique=True)
    op.create_table(
        "components",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_name"],
            ["libraries.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_components_filename"), "components", ["filename"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_components_filename"), table_name="components")
    op.drop_table("components")
    op.drop_index(op.f("ix_libraries_name"), table_name="libraries")
    op.drop_table("libraries")
    # ### end Alembic commands ###
