"""Update endpoints

Revision ID: 80fc695fabfd
Revises: 77f096106bb3
Create Date: 2023-03-25 17:38:42.197124

"""


# revision identifiers, used by Alembic.
revision = "80fc695fabfd"
down_revision = "77f096106bb3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
