"""update

Revision ID: 08d982dc70de
Revises: dd8eb1dea37f
Create Date: 2024-06-09 15:39:42.393581

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "08d982dc70de"
down_revision = "dd8eb1dea37f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_components_jsonfile", table_name="components")
    op.create_index(
        op.f("ix_components_jsonfile"), "components", ["jsonfile"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_components_jsonfile"), table_name="components")
    op.create_index("ix_components_jsonfile", "components", ["jsonfile"], unique=True)
    # ### end Alembic commands ###
