from enum import Enum


class ComponentStatus(str, Enum):
    DELETED = "DELETED"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class ComponentDownloadStatus(str, Enum):
    COMPLETED = "COMPLETED"
    FAILED_AUTHENTICATION = "FAILED_AUTHENTICATION"
    FAILED_NOT_ENTITLED = "FAILED_NOT_ENTITLED"
    FAILED_CHECKSUM = "FAILED_CHECKSUM"
    FAILED_UNKNOWN = "FAILED_UNKNOWN"
    NOT_STARTED = "NOT_STARTED"
    SCHEDULED = "SCHEDULED"


class InstanceComponentStatus(str, Enum):
    ACTIVE = "ACTIVE"
    BUILDING = "BUILDING"
    ADD_FAILED = "ADD_FAILED"
    DELETE_FAILED = "DELETE_FAILED"


class InstancePermission(str, Enum):
    INSTANCE_ADMIN = "INSTANCE_ADMIN"
    INSTANCE_OWNER = "INSTANCE_OWNER"
    INSTANCE_READ_ONLY = "INSTANCE_READ_ONLY"


class InstanceStatus(str, Enum):
    ACTIVE = "ACTIVE"
    BUILDING = "BUILDING"
    DELETED = "DELETED"
    DELETING = "DELETING"
    DEPLOY_FAILED = "DEPLOY_FAILED"
    DESTROY_FAILED = "DESTROY_FAILED"
    PENDING = "PENDING"
