from enum import Enum


class ComponentStatus(str, Enum):
    FAILED_DOWNLOAD = "FAILED_DOWNLOAD"
    NOT_ENTITLED = "NOT_ENTITLED"
    DOWNLOAD_COMPLETE = "DOWNLOAD_COMPLETE"
    FAILED_AUTHENTICATION = "FAILED_AUTHENTICATION"
    SCHEDULED = "SCHEDULED"
    DOWNLOAD_INCOMPLETE = "DOWNLOAD_INCOMPLETE"
    DELETED = "DELETED"


class InstanceComponentStatus(str, Enum):
    ACTIVE = "ACTIVE"
    BUILDING = "BUILDING"
    ADD_FAILED = "ADD_FAILED"
    DELETE_FAILED = "DELETE_FAILED"


class InstancePermission(str, Enum):
    INSTANCE_ADMIN = "INSTANCE_ADMIN"
    INSTANCE_OWNER = "INSTANCE_OWNER"
    INSTANCE_READ_ONLY = "INSTANCE_READ_ONLY"


class InstanceStatus(str, Enum):
    ACTIVE = "ACTIVE"
    BUILDING = "BUILDING"
    DELETED = "DELETED"
    DELETING = "DELETING"
    DEPLOY_FAILED = "DEPLOY_FAILED"
    DESTROY_FAILED = "DESTROY_FAILED"
    PENDING = "PENDING"
