"""Smoke tests for the auto-generated zpodsdk client.

The SDK is mostly generated by openapi-python-client, so these tests just
verify the package imports cleanly and a representative slice of the public
surface (clients + a few models) instantiates without error.
"""

from zpodsdk import AuthenticatedClient, Client
from zpodsdk.models.user_create import UserCreate


def test_client_instantiation():
    client = Client(base_url="http://localhost:8000")
    assert client is not None


def test_authenticated_client_instantiation():
    client = AuthenticatedClient(
        base_url="http://localhost:8000",
        token="dummy-token",
    )
    assert client is not None


def test_user_create_model():
    user = UserCreate(
        username="testuser",
        email="testuser@example.com",
    )
    assert user.username == "testuser"
    assert user.email == "testuser@example.com"
