project_name_override: zpodsdk/src
package_name_override: zpodsdk

class_overrides:
  EndpointENetCreate:
    module_name: endpoint_enet_create
  EndpointENetView:
    module_name: endpoint_enet_view

post_hooks:
  - python /zpodcore/zpodsdk_builder/build_client.py "zpodsdk" --class_name ZpodClient
  - ruff --fix --extend-select "I" .
  - ruff format .
