project_name_override: zpodsdk
package_name_override: zpod

post_hooks:
  - python /zpodcore/zpodsdk_builder/build_client.py "zpod"
  - autoflake -i -r --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports .
  - isort .
  - black .
