project_name_override: zpodsdk
package_name_override: zpod

class_overrides:
  EndpointENetCreate:
    module_name: endpoint_enet_create
  EndpointENetView:
    module_name: endpoint_enet_view

post_hooks:
  - python /zpodcore/zpodsdk_builder/build_client.py "zpod"
  - ruff --fix --extend-select "I" .
  - ruff format .
