FROM python:3.10.7-slim as requirements-stage
WORKDIR /tmp
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir poetry
COPY pyproject.toml poetry.lock* /tmp/
ARG INSTALL_DEV=false
RUN bash -c "if [ $INSTALL_DEV == 'true' ] ; then poetry export --dev -f requirements.txt --output requirements.txt --without-hashes ; else poetry export -f requirements.txt --output requirements.txt --without-hashes ; fi"

# BASE
FROM python:3.10-slim as base
RUN pip install --no-cache-dir --upgrade pip
WORKDIR /zpodcore/zpodsdk_builder
ENV PYTHONPATH=/zpodcore/zpodsdk_builder
COPY --from=requirements-stage /tmp/requirements.txt /requirements.txt
RUN pip install --no-cache-dir --upgrade -r /requirements.txt
CMD ["tail", "-f", "/dev/null"]

# PROD
FROM base as production
COPY . /zpodcore/zpodsdk_builder
CMD ["bash", "-c", "openapi-python-client generate --path openapi.json --config config.yaml"]